title: "eimertvink.nl | humble thoughts and tech tips"
description: "🇳🇱 Cloud Engineer. Passionate about Linux and Java. Curious and eager to learn."
name: "Eimert Vink"
# set default author
author: Eimert Vink
show_downloads: false
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jemoji
minimal_mistakes_skin: "sunrise" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
# pagination size
paginate: 20
locale: "en"
# enable when the migration to github pages is done.
url: "https://eimertvink.nl"
# wip: devise new logo #logo: "/assets/images/88x88.png"
include: ["_pages"]

atom_feed:
  path: # blank (default) uses /feed.xml

# recommended front matter defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

compress_html:
  clippings: all
  ignore:
    envs: development

comments:
  provider               : "disqus"
  disqus:
    shortname            : "eimertvink"

analytics:
  provider: "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id: UA-65648916-1

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

# Site Footer
footer:
  links:
    - label: "Keybase"
      icon: "fab fa-fw fa-keybase"
      url: "https://keybase.io/eimert"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-github"
      url: "https://linkedin.com/in/eimertvink"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Eimert"

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/