title: "eimertvink.nl | humble thoughts and tech tips"
description: "🇳🇱 Java Developer. Passionate about Linux and Java. Curious and eager to learn."
name: "Eimert Vink"
show_downloads: false
remote_theme: "mmistakes/minimal-mistakes@4.16.0"
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "contrast" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
analytics:
  provider: "google-gtag"
  google:
  tracking_id: "UA-65648916-1"
  anonymize_ip: false # default
locale: "en-GB"
# enable when the migration to github pages is done.
# url: "https://eimertvink.nl"
# wip: devise new logo
#logo: "/assets/images/88x88.png"
include: ["_pages"]

# recommended front matter defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
paginate: 5
# seems to slow down jekyll serve:
author: Eimert Vink
compress_html:
  clippings: all
  ignore:
    envs: development